version: '3.8'

services:
  server:
    build: .  #dockerfile위치
    image: ChatKiosk-Server
    volumes:  #디렉터리생성
      - /home/cupokki/Workspace/ChatKiosk/server:/app
    ports:
      - 8000:8000
    command: npm start

