version: '3.8'

services:
  server:
    build: .  #dockerfile위치
    image: chat-kiosk-server
    volumes:  #디렉터리생성
      - .:/app
    ports:
      - 8000:8000
    command: sh -c "npm i && npm start"

